[package]
name = "session_tracker"
version.workspace = true
edition = "2024"
description = "Session and lifetime GW2 stat tracker"
authors = ["SpiroTris.3748"]

[lib]
crate-type = ["cdylib"]

[dependencies]
session_tracker_core = { path = "../core" }
session_tracker_net = { path = "../net" }
nexus = { git = "https://github.com/Zerthox/nexus-rs", features = ["log", "log_filter", "mumble"] }
log = "0.4"
